name: PocketJobsPlus
main: popkechupki\PocketJobsPlus
version: 0.1.3.AmberMoney
api: [1.13.0, 2.0.0, 3.0.0]
load: POSTWORLD
author: popkechupki
description: "AmberMoneyに対応した職業プラグイン。"
web: "http://github.com/popkechupki/PocketJobsPlus"
