name: PocketJobsPlus
main: popkechupki\base
version: 0.1
api: [1.13.0,2.0.0]
load: POSTWORLD
author: popkechupki
description: "PocketMoneyに対応した職業プラグイン。"
web: "https://github.com/popkechupki/PocketJobsPlus"