name: PocketJobsPlus
main: popkechupki\PocketJobsPlus
version: 0.1.Economy
api: [1.13.0, 2.0.0]
load: POSTWORLD
author: popkechupki
description: "PocketMoneyに対応した職業プラグイン。"
web: "http://github.com/PocketJobsPlus"